import React from 'react'
import {
  LayoutDashboard, FileText, BarChart2, MessageSquare,
  CheckSquare, Settings, Search, Bell, ChevronDown,
  ChevronRight, Plus, X, Check, AlertCircle, Info,
  Upload, Download, Eye, Edit2, Trash2, Send,
  Users, Building2, ArrowUpRight, ArrowDownRight,
  Sparkles, Shield, Clock, Calendar, Filter,
  MoreHorizontal, LogOut, Menu, RefreshCw,
} from 'lucide-react'

type IconProps = { size?: number; color?: string }

export const Icon = {
  Dashboard:   (p: IconProps) => <LayoutDashboard size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Document:    (p: IconProps) => <FileText        size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Report:      (p: IconProps) => <BarChart2       size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  WhatsApp:    (p: IconProps) => <MessageSquare   size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Compliance:  (p: IconProps) => <CheckSquare     size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Settings:    (p: IconProps) => <Settings        size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Search:      (p: IconProps) => <Search          size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Bell:        (p: IconProps) => <Bell            size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Plus:        (p: IconProps) => <Plus            size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Close:       (p: IconProps) => <X               size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Check:       (p: IconProps) => <Check           size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Alert:       (p: IconProps) => <AlertCircle     size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Info:        (p: IconProps) => <Info            size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Upload:      (p: IconProps) => <Upload          size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Download:    (p: IconProps) => <Download        size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Eye:         (p: IconProps) => <Eye             size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Edit:        (p: IconProps) => <Edit2           size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Delete:      (p: IconProps) => <Trash2          size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Send:        (p: IconProps) => <Send            size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  AI:          (p: IconProps) => <Sparkles        size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Shield:      (p: IconProps) => <Shield          size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Filter:      (p: IconProps) => <Filter          size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  More:        (p: IconProps) => <MoreHorizontal  size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Refresh:     (p: IconProps) => <RefreshCw       size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  TrendUp:     (p: IconProps) => <ArrowUpRight    size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  TrendDown:   (p: IconProps) => <ArrowDownRight  size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Collections: (p: IconProps) => <Building2       size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Team:        (p: IconProps) => <Users           size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Calendar:    (p: IconProps) => <Calendar        size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Clock:       (p: IconProps) => <Clock           size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  ChevronDown: (p: IconProps) => <ChevronDown     size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  ChevronRight:(p: IconProps) => <ChevronRight    size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  Menu:        (p: IconProps) => <Menu            size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
  LogOut:      (p: IconProps) => <LogOut          size={p.size||16} color={p.color||'currentColor'} strokeWidth={2}/>,
}
