export { PrismaClient, Prisma } from '@prisma/client';
export type {
  Company,
  User,
  Invoice,
  CollectionRisk,
  InventoryItem,
  AIInsight,
  AuditLog,
  BusinessConfig,
  Document,
  DocumentRequest,
  Report,
  WhatsAppMessage,
  WhatsAppTemplate,
  KnowledgeDocument,
  KnowledgeChunk,
  AssistantConversation,
  AssistantMessage,
  Client,
  SystemConfig,
  ClientConfig,
  TaxIntegration,
  TaxSyncLog,
} from '@prisma/client';

// Enums must be exported as values (not `export type`) so @IsEnum() decorators work at runtime
export {
  Industry,
  SubscriptionPlan,
  UserRole,
  InvoiceStatus,
  AIModule,
  InsightSeverity,
  DocumentType,
  DocumentStatus,
  RequestStatus,
  ReportType,
  ReportStatus,
  MessageDirection,
  MessageStatus,
  KnowledgeCategory,
  MessageRole,
  FilerType,
  FilingCategory,
  ConfigDataType,
  ConfigCategory,
  TaxProvider,
  SyncStatus,
} from '@prisma/client';
