import { Injectable, NotFoundException } from '@nestjs/common'
import { PrismaService } from '../../prisma/prisma.service'
import PDFDocument from 'pdfkit'
import ExcelJS from 'exceljs'
import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, WidthType, AlignmentType, BorderStyle } from 'docx'
import type { ReportType } from '@opsc/database'

// ── Colour palette (used across all formats) ───────────────────────────────────
const BRAND_BLUE  = '#1e40af'
const LIGHT_GRAY  = '#f3f4f6'
const MID_GRAY    = '#6b7280'
const RED         = '#dc2626'
const AMBER       = '#d97706'
const GREEN       = '#16a34a'

const REPORT_LABEL: Record<ReportType, string> = {
  COLLECTIONS_AGING:   'Collections Aging Report',
  RECEIVABLES_SUMMARY: 'Receivables Summary Report',
  INVENTORY_STATUS:    'Inventory Status Report',
  CASH_FLOW:           'Cash Flow Report',
  AI_INSIGHTS_DIGEST:  'AI Insights Digest',
}

/** Report types that have tabular rows suitable for Excel */
const TABULAR_TYPES: ReportType[] = ['COLLECTIONS_AGING', 'RECEIVABLES_SUMMARY', 'INVENTORY_STATUS']

@Injectable()
export class ReportExportService {
  constructor(private readonly prisma: PrismaService) {}

  // ── Public entry points ────────────────────────────────────────────────────

  async exportPdf(reportId: string, companyId: string): Promise<Buffer> {
    const { report, company } = await this.load(reportId, companyId)
    return this.buildPdf(report, company.name)
  }

  async exportExcel(reportId: string, companyId: string): Promise<Buffer> {
    const { report, company } = await this.load(reportId, companyId)
    if (!TABULAR_TYPES.includes(report.reportType as ReportType)) {
      throw new NotFoundException('Excel export is only available for tabular report types')
    }
    return this.buildExcel(report, company.name)
  }

  async exportWord(reportId: string, companyId: string): Promise<Buffer> {
    const { report, company } = await this.load(reportId, companyId)
    return this.buildWord(report, company.name)
  }

  // ── Loader ─────────────────────────────────────────────────────────────────

  private async load(reportId: string, companyId: string) {
    const report = await this.prisma.report.findUnique({ where: { id: reportId } })
    if (!report || report.companyId !== companyId) throw new NotFoundException('Report not found')
    if (report.status !== 'COMPLETED') throw new NotFoundException('Report is not yet completed')

    const company = await this.prisma.company.findUniqueOrThrow({
      where: { id: companyId },
      select: { name: true },
    })
    return { report, company }
  }

  // ── PDF ────────────────────────────────────────────────────────────────────

  private buildPdf(report: { reportType: string; aiSummary: string | null; dataSnapshot: unknown; createdAt: Date }, companyName: string): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' })
      const chunks: Buffer[] = []
      doc.on('data', (c: Buffer) => chunks.push(c))
      doc.on('end', () => resolve(Buffer.concat(chunks)))
      doc.on('error', reject)

      const title = REPORT_LABEL[report.reportType as ReportType] ?? report.reportType.replace(/_/g, ' ')
      const data  = report.dataSnapshot as Record<string, unknown>

      // ── Header ──────────────────────────────────────────────────────────────
      doc.rect(0, 0, doc.page.width, 90).fill(BRAND_BLUE)
      doc.fillColor('white').fontSize(20).font('Helvetica-Bold').text(title, 50, 28)
      doc.fontSize(10).font('Helvetica').text(companyName, 50, 54)
      doc.text(`Generated: ${new Date(report.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, 50, 68)
      doc.fillColor('black').moveDown(3)

      // ── AI Summary ──────────────────────────────────────────────────────────
      if (report.aiSummary) {
        doc.rect(50, doc.y, doc.page.width - 100, 12).fill(LIGHT_GRAY)
        doc.fillColor(BRAND_BLUE).fontSize(11).font('Helvetica-Bold').text('Executive Summary', 55, doc.y - 10)
        doc.fillColor('black').fontSize(10).font('Helvetica')
          .text(report.aiSummary, 50, doc.y + 6, { width: doc.page.width - 100 })
        doc.moveDown(1.5)
      }

      // ── Data section ─────────────────────────────────────────────────────────
      this.pdfDataSection(doc, report.reportType as ReportType, data)

      // ── Footer ───────────────────────────────────────────────────────────────
      doc.fontSize(8).fillColor(MID_GRAY)
        .text(`Generated by OpsCopilot · ${companyName}`, 50, doc.page.height - 40, { align: 'center', width: doc.page.width - 100 })

      doc.end()
    })
  }

  private pdfDataSection(doc: InstanceType<typeof PDFDocument>, type: ReportType, data: Record<string, unknown>) {
    const h = (text: string) => {
      doc.fillColor(BRAND_BLUE).fontSize(12).font('Helvetica-Bold').text(text)
      doc.fillColor('black').fontSize(10).font('Helvetica').moveDown(0.5)
    }
    const kv = (label: string, value: string) => {
      doc.font('Helvetica-Bold').text(`${label}: `, { continued: true })
         .font('Helvetica').text(value).moveDown(0.2)
    }

    if (type === 'COLLECTIONS_AGING') {
      const d = data as { totalOverdue: number; overdueCount: number; buckets: { label: string; count: number; amount: number }[] }
      h('Overdue Summary')
      kv('Total overdue', `₹${Number(d.totalOverdue).toLocaleString('en-IN')}`)
      kv('Overdue invoices', String(d.overdueCount))
      doc.moveDown(0.5)
      h('Aging Buckets')
      this.pdfTable(doc,
        ['Bucket', 'Count', 'Amount (₹)'],
        d.buckets.map((b) => [b.label, String(b.count), Number(b.amount).toLocaleString('en-IN')]),
      )
    }

    if (type === 'RECEIVABLES_SUMMARY') {
      const d = data as { totalAmount: number; totalInvoices: number; avgAgingDays: number; byStatus: { status: string; count: number; amount: number }[] }
      h('Receivables Summary')
      kv('Total receivables', `₹${Number(d.totalAmount).toLocaleString('en-IN')}`)
      kv('Total invoices', String(d.totalInvoices))
      kv('Avg aging', `${d.avgAgingDays} days`)
      doc.moveDown(0.5)
      h('By Status')
      this.pdfTable(doc,
        ['Status', 'Count', 'Amount (₹)'],
        d.byStatus.map((s) => [s.status, String(s.count), Number(s.amount).toLocaleString('en-IN')]),
      )
    }

    if (type === 'INVENTORY_STATUS') {
      const d = data as { totalItems: number; lowStockCount: number; totalInventoryValue: number; lowStockItems: { sku: string; name: string; quantity: number; reorderLevel: number; daysUntilStockout: number | null }[] }
      h('Inventory Summary')
      kv('Total items', String(d.totalItems))
      kv('Low-stock items', String(d.lowStockCount))
      kv('Total inventory value', `₹${Number(d.totalInventoryValue).toLocaleString('en-IN')}`)
      doc.moveDown(0.5)
      if (d.lowStockItems.length > 0) {
        h('Low-Stock Items')
        this.pdfTable(doc,
          ['SKU', 'Name', 'Qty', 'Reorder Level', 'Days to Stockout'],
          d.lowStockItems.map((i) => [i.sku, i.name, String(i.quantity), String(i.reorderLevel), i.daysUntilStockout != null ? String(i.daysUntilStockout) : '—']),
        )
      }
    }

    if (type === 'CASH_FLOW') {
      const d = data as { collectedAmount: number; collectedCount: number; pendingAmount: number; pendingCount: number }
      h('Cash Flow Summary')
      kv('Collected', `₹${Number(d.collectedAmount).toLocaleString('en-IN')} (${d.collectedCount} invoices)`)
      kv('Pending', `₹${Number(d.pendingAmount).toLocaleString('en-IN')} (${d.pendingCount} invoices)`)
      const total = d.collectedAmount + d.pendingAmount
      const rate = total > 0 ? Math.round((d.collectedAmount / total) * 100) : 0
      kv('Collection rate', `${rate}%`)
    }

    if (type === 'AI_INSIGHTS_DIGEST') {
      const d = data as {
        totalInsights: number
        bySeverity: { CRITICAL: number; WARNING: number; INFO: number }
        recentInsights: { module: string; category: string; severity: string; summary: string; createdAt: string }[]
        complianceReadiness?: {
          totalChecklists: number
          avgReadinessScore: number | null
          overdueCount: number
          readyCount: number
          checklists: { clientName: string; label: string; dueDate: string; readinessScore: number; status: string; missingCount: number }[]
        }
      }
      h('Insights Summary')
      kv('Total insights', String(d.totalInsights))
      kv('Critical', String(d.bySeverity.CRITICAL))
      kv('Warnings', String(d.bySeverity.WARNING))
      kv('Info', String(d.bySeverity.INFO))
      doc.moveDown(0.5)
      if (d.recentInsights.length > 0) {
        h('Recent Insights')
        for (const ins of d.recentInsights.slice(0, 10)) {
          doc.font('Helvetica-Bold').text(`[${ins.severity}] ${ins.module}`, { continued: true })
             .font('Helvetica').text(` — ${ins.summary}`, { width: doc.page.width - 100 }).moveDown(0.3)
        }
      }
      if (d.complianceReadiness && d.complianceReadiness.totalChecklists > 0) {
        doc.moveDown(0.5)
        h('Compliance Readiness')
        kv('Active checklists', String(d.complianceReadiness.totalChecklists))
        if (d.complianceReadiness.avgReadinessScore !== null) {
          kv('Average readiness', `${d.complianceReadiness.avgReadinessScore}%`)
        }
        kv('Overdue', String(d.complianceReadiness.overdueCount))
        kv('Ready to file', String(d.complianceReadiness.readyCount))
        if (d.complianceReadiness.checklists.length > 0) {
          doc.moveDown(0.5)
          this.pdfTable(doc,
            ['Client', 'Filing', 'Due Date', 'Readiness', 'Status'],
            d.complianceReadiness.checklists.map((c) => [
              c.clientName,
              c.label,
              c.dueDate,
              `${c.readinessScore}%`,
              c.status.replace('_', ' '),
            ]),
          )
        }
      }
    }
  }

  private pdfTable(doc: InstanceType<typeof PDFDocument>, headers: string[], rows: string[][]) {
    const colWidth = (doc.page.width - 100) / headers.length
    const startX = 50
    let y = doc.y

    // Header row
    doc.rect(startX, y, doc.page.width - 100, 18).fill(BRAND_BLUE)
    headers.forEach((h, i) => {
      doc.fillColor('white').font('Helvetica-Bold').fontSize(9)
         .text(h, startX + i * colWidth + 4, y + 4, { width: colWidth - 8 })
    })
    y += 18

    // Data rows
    rows.forEach((row, ri) => {
      doc.rect(startX, y, doc.page.width - 100, 16).fill(ri % 2 === 0 ? LIGHT_GRAY : 'white')
      row.forEach((cell, i) => {
        doc.fillColor('black').font('Helvetica').fontSize(9)
           .text(cell, startX + i * colWidth + 4, y + 3, { width: colWidth - 8 })
      })
      y += 16
    })

    doc.y = y + 8
    doc.moveDown(0.5)
  }

  // ── Excel ──────────────────────────────────────────────────────────────────

  private async buildExcel(
    report: { reportType: string; aiSummary: string | null; dataSnapshot: unknown; createdAt: Date },
    companyName: string,
  ): Promise<Buffer> {
    const wb = new ExcelJS.Workbook()
    wb.creator = companyName
    wb.created = new Date(report.createdAt)

    const title  = REPORT_LABEL[report.reportType as ReportType] ?? report.reportType
    const ws     = wb.addWorksheet(title.slice(0, 31))
    const data   = report.dataSnapshot as Record<string, unknown>

    // Styles
    const titleStyle: Partial<ExcelJS.Style> = {
      font: { bold: true, size: 14, color: { argb: 'FF1E40AF' } },
    }
    const headerStyle: Partial<ExcelJS.Style> = {
      font: { bold: true, color: { argb: 'FFFFFFFF' } },
      fill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E40AF' } },
      alignment: { horizontal: 'center' },
      border: {
        bottom: { style: 'thin', color: { argb: 'FFE5E7EB' } },
      },
    }
    const altRowFill: ExcelJS.Fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF3F4F6' } }

    // Title
    ws.mergeCells('A1:F1')
    ws.getCell('A1').value = title
    ws.getCell('A1').style = titleStyle
    ws.getRow(1).height = 24

    ws.getCell('A2').value = companyName
    ws.getCell('A2').font = { italic: true, color: { argb: 'FF6B7280' } }
    ws.getCell('A3').value = `Generated: ${new Date(report.createdAt).toLocaleDateString('en-IN')}`
    ws.getCell('A3').font = { italic: true, color: { argb: 'FF6B7280' } }

    if (report.aiSummary) {
      ws.getRow(4).height = 14
      ws.getCell('A5').value = 'AI Summary:'
      ws.getCell('A5').font = { bold: true }
      ws.mergeCells('B5:F5')
      ws.getCell('B5').value = report.aiSummary
      ws.getCell('B5').alignment = { wrapText: true }
    }

    const dataStartRow = report.aiSummary ? 7 : 5

    if (report.reportType === 'COLLECTIONS_AGING') {
      const d = data as { buckets: { label: string; count: number; amount: number }[] }
      this.excelTable(ws, dataStartRow, ['Aging Bucket', 'Invoice Count', 'Amount (₹)'], headerStyle, altRowFill,
        d.buckets.map((b) => [b.label, b.count, b.amount]),
      )
      ws.getColumn(1).width = 20
      ws.getColumn(2).width = 15
      ws.getColumn(3).width = 18
    }

    if (report.reportType === 'RECEIVABLES_SUMMARY') {
      const d = data as { byStatus: { status: string; count: number; amount: number }[] }
      this.excelTable(ws, dataStartRow, ['Status', 'Invoice Count', 'Amount (₹)'], headerStyle, altRowFill,
        d.byStatus.map((s) => [s.status, s.count, s.amount]),
      )
      ws.getColumn(1).width = 15
      ws.getColumn(2).width = 15
      ws.getColumn(3).width = 18
    }

    if (report.reportType === 'INVENTORY_STATUS') {
      const d = data as { lowStockItems: { sku: string; name: string; quantity: number; reorderLevel: number; daysUntilStockout: number | null }[] }
      this.excelTable(ws, dataStartRow,
        ['SKU', 'Item Name', 'Qty in Stock', 'Reorder Level', 'Days to Stockout'],
        headerStyle, altRowFill,
        d.lowStockItems.map((i) => [i.sku, i.name, i.quantity, i.reorderLevel, i.daysUntilStockout ?? 'N/A']),
      )
      ws.getColumn(1).width = 14
      ws.getColumn(2).width = 30
      ws.getColumn(3).width = 14
      ws.getColumn(4).width = 14
      ws.getColumn(5).width = 16
    }

    if (report.reportType === 'AI_INSIGHTS_DIGEST') {
      const d = data as {
        totalInsights: number
        bySeverity: { CRITICAL: number; WARNING: number; INFO: number }
        recentInsights: { module: string; severity: string; summary: string }[]
        complianceReadiness?: {
          totalChecklists: number
          avgReadinessScore: number | null
          overdueCount: number
          readyCount: number
          checklists: { clientName: string; label: string; dueDate: string; readinessScore: number; status: string; missingCount: number }[]
        }
      }

      // Sheet 1 (ws): Insights summary + table
      this.excelTable(ws, dataStartRow,
        ['Severity', 'Count'],
        headerStyle, altRowFill,
        [
          ['CRITICAL', d.bySeverity.CRITICAL],
          ['WARNING', d.bySeverity.WARNING],
          ['INFO', d.bySeverity.INFO],
        ],
      )
      ws.getColumn(1).width = 14
      ws.getColumn(2).width = 12

      // Sheet 2: Recent Insights
      if (d.recentInsights.length > 0) {
        const ws2 = wb.addWorksheet('Recent Insights')
        ws2.mergeCells('A1:C1')
        ws2.getCell('A1').value = 'Recent Insights'
        ws2.getCell('A1').style = titleStyle
        ws2.getRow(1).height = 24
        this.excelTable(ws2, 3, ['Module', 'Severity', 'Summary'], headerStyle, altRowFill,
          d.recentInsights.slice(0, 20).map((i) => [i.module, i.severity, i.summary]),
        )
        ws2.getColumn(1).width = 18
        ws2.getColumn(2).width = 12
        ws2.getColumn(3).width = 60
      }

      // Sheet 3: Compliance Readiness
      if (d.complianceReadiness && d.complianceReadiness.totalChecklists > 0) {
        const ws3 = wb.addWorksheet('Compliance Readiness')
        ws3.mergeCells('A1:F1')
        ws3.getCell('A1').value = 'Compliance Readiness'
        ws3.getCell('A1').style = titleStyle
        ws3.getRow(1).height = 24
        ws3.getCell('A2').value = `Active checklists: ${d.complianceReadiness.totalChecklists}`
        ws3.getCell('A2').font = { italic: true, color: { argb: 'FF6B7280' } }
        ws3.getCell('A3').value = `Avg readiness: ${d.complianceReadiness.avgReadinessScore ?? 'N/A'}%   Overdue: ${d.complianceReadiness.overdueCount}   Ready: ${d.complianceReadiness.readyCount}`
        ws3.getCell('A3').font = { italic: true, color: { argb: 'FF6B7280' } }
        this.excelTable(ws3, 5,
          ['Client', 'Filing', 'Due Date', 'Readiness %', 'Status', 'Missing Docs'],
          headerStyle, altRowFill,
          d.complianceReadiness.checklists.map((c) => [
            c.clientName, c.label, c.dueDate, c.readinessScore, c.status, c.missingCount,
          ]),
        )
        ws3.getColumn(1).width = 22
        ws3.getColumn(2).width = 28
        ws3.getColumn(3).width = 14
        ws3.getColumn(4).width = 14
        ws3.getColumn(5).width = 14
        ws3.getColumn(6).width = 14
      }
    }

    const buf = await wb.xlsx.writeBuffer()
    return Buffer.from(buf)
  }

  private excelTable(
    ws: ExcelJS.Worksheet,
    startRow: number,
    headers: string[],
    headerStyle: Partial<ExcelJS.Style>,
    altFill: ExcelJS.Fill,
    rows: (string | number)[][],
  ) {
    const hRow = ws.getRow(startRow)
    headers.forEach((h, i) => {
      hRow.getCell(i + 1).value = h
      hRow.getCell(i + 1).style = headerStyle
    })
    hRow.height = 18

    rows.forEach((row, ri) => {
      const r = ws.getRow(startRow + 1 + ri)
      row.forEach((cell, ci) => {
        r.getCell(ci + 1).value = cell
        if (ri % 2 === 0) r.getCell(ci + 1).fill = altFill
      })
    })
  }

  // ── Word ───────────────────────────────────────────────────────────────────

  private async buildWord(
    report: { reportType: string; aiSummary: string | null; dataSnapshot: unknown; createdAt: Date },
    companyName: string,
  ): Promise<Buffer> {
    const title = REPORT_LABEL[report.reportType as ReportType] ?? report.reportType.replace(/_/g, ' ')
    const data  = report.dataSnapshot as Record<string, unknown>

    const children: (Paragraph | Table)[] = []

    // Title
    children.push(new Paragraph({
      text: title,
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 120 },
    }))
    children.push(new Paragraph({
      children: [
        new TextRun({ text: companyName, color: '6B7280', italics: true }),
        new TextRun({ text: '   ', break: 0 }),
        new TextRun({ text: `Generated: ${new Date(report.createdAt).toLocaleDateString('en-IN')}`, color: '6B7280', italics: true }),
      ],
      spacing: { after: 240 },
    }))

    // AI Summary
    if (report.aiSummary) {
      children.push(new Paragraph({ text: 'Executive Summary', heading: HeadingLevel.HEADING_2 }))
      children.push(new Paragraph({
        children: [new TextRun({ text: report.aiSummary, color: '1E3A5F' })],
        spacing: { after: 240 },
      }))
    }

    // Data
    this.wordDataSection(children, report.reportType as ReportType, data)

    // Footer
    children.push(new Paragraph({
      children: [new TextRun({ text: `Generated by OpsCopilot · ${companyName}`, color: '9CA3AF', size: 16 })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 480 },
    }))

    const docx = new Document({ sections: [{ children }] })
    return Packer.toBuffer(docx)
  }

  private wordDataSection(
    children: (Paragraph | Table)[],
    type: ReportType,
    data: Record<string, unknown>,
  ) {
    const h2 = (text: string) => new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { after: 120 } })
    const kv = (label: string, value: string) => new Paragraph({
      children: [
        new TextRun({ text: `${label}: `, bold: true }),
        new TextRun({ text: value }),
      ],
      spacing: { after: 80 },
    })

    if (type === 'COLLECTIONS_AGING') {
      const d = data as { totalOverdue: number; overdueCount: number; buckets: { label: string; count: number; amount: number }[] }
      children.push(h2('Overdue Summary'))
      children.push(kv('Total overdue', `₹${Number(d.totalOverdue).toLocaleString('en-IN')}`))
      children.push(kv('Overdue invoices', String(d.overdueCount)))
      children.push(h2('Aging Buckets'))
      children.push(this.wordTable(['Bucket', 'Count', 'Amount (₹)'],
        d.buckets.map((b) => [b.label, String(b.count), Number(b.amount).toLocaleString('en-IN')]),
      ))
    }

    if (type === 'RECEIVABLES_SUMMARY') {
      const d = data as { totalAmount: number; totalInvoices: number; avgAgingDays: number; byStatus: { status: string; count: number; amount: number }[] }
      children.push(h2('Receivables Summary'))
      children.push(kv('Total receivables', `₹${Number(d.totalAmount).toLocaleString('en-IN')}`))
      children.push(kv('Total invoices', String(d.totalInvoices)))
      children.push(kv('Avg aging', `${d.avgAgingDays} days`))
      children.push(h2('By Status'))
      children.push(this.wordTable(['Status', 'Count', 'Amount (₹)'],
        d.byStatus.map((s) => [s.status, String(s.count), Number(s.amount).toLocaleString('en-IN')]),
      ))
    }

    if (type === 'INVENTORY_STATUS') {
      const d = data as { totalItems: number; lowStockCount: number; totalInventoryValue: number; lowStockItems: { sku: string; name: string; quantity: number; reorderLevel: number; daysUntilStockout: number | null }[] }
      children.push(h2('Inventory Summary'))
      children.push(kv('Total items', String(d.totalItems)))
      children.push(kv('Low-stock items', String(d.lowStockCount)))
      children.push(kv('Total inventory value', `₹${Number(d.totalInventoryValue).toLocaleString('en-IN')}`))
      if (d.lowStockItems.length > 0) {
        children.push(h2('Low-Stock Items'))
        children.push(this.wordTable(
          ['SKU', 'Name', 'Qty', 'Reorder Level', 'Days to Stockout'],
          d.lowStockItems.map((i) => [i.sku, i.name, String(i.quantity), String(i.reorderLevel), i.daysUntilStockout != null ? String(i.daysUntilStockout) : '—']),
        ))
      }
    }

    if (type === 'CASH_FLOW') {
      const d = data as { collectedAmount: number; collectedCount: number; pendingAmount: number; pendingCount: number }
      children.push(h2('Cash Flow Summary'))
      children.push(kv('Collected', `₹${Number(d.collectedAmount).toLocaleString('en-IN')} (${d.collectedCount} invoices)`))
      children.push(kv('Pending', `₹${Number(d.pendingAmount).toLocaleString('en-IN')} (${d.pendingCount} invoices)`))
      const total = d.collectedAmount + d.pendingAmount
      children.push(kv('Collection rate', `${total > 0 ? Math.round((d.collectedAmount / total) * 100) : 0}%`))
    }

    if (type === 'AI_INSIGHTS_DIGEST') {
      const d = data as {
        totalInsights: number
        bySeverity: { CRITICAL: number; WARNING: number; INFO: number }
        recentInsights: { module: string; category: string; severity: string; summary: string }[]
        complianceReadiness?: {
          totalChecklists: number
          avgReadinessScore: number | null
          overdueCount: number
          readyCount: number
          checklists: { clientName: string; label: string; dueDate: string; readinessScore: number; status: string; missingCount: number }[]
        }
      }
      children.push(h2('Insights Summary'))
      children.push(kv('Total', String(d.totalInsights)))
      children.push(kv('Critical', String(d.bySeverity.CRITICAL)))
      children.push(kv('Warnings', String(d.bySeverity.WARNING)))
      children.push(kv('Info', String(d.bySeverity.INFO)))
      if (d.recentInsights.length > 0) {
        children.push(h2('Recent Insights'))
        for (const ins of d.recentInsights.slice(0, 15)) {
          children.push(new Paragraph({
            children: [
              new TextRun({ text: `[${ins.severity}] ${ins.module}  `, bold: true }),
              new TextRun({ text: ins.summary }),
            ],
            spacing: { after: 80 },
          }))
        }
      }
      if (d.complianceReadiness && d.complianceReadiness.totalChecklists > 0) {
        const cr = d.complianceReadiness
        children.push(h2('Compliance Readiness'))
        children.push(kv('Active checklists', String(cr.totalChecklists)))
        children.push(kv('Avg readiness score', cr.avgReadinessScore != null ? `${cr.avgReadinessScore}%` : 'N/A'))
        children.push(kv('Overdue', String(cr.overdueCount)))
        children.push(kv('Ready to file', String(cr.readyCount)))
        if (cr.checklists.length > 0) {
          children.push(new Paragraph({ text: '', spacing: { after: 80 } }))
          children.push(this.wordTable(
            ['Client', 'Filing', 'Due Date', 'Readiness', 'Status', 'Missing'],
            cr.checklists.map((c) => [
              c.clientName, c.label, c.dueDate, `${c.readinessScore}%`, c.status, String(c.missingCount),
            ]),
          ))
        }
      }
    }
  }

  private wordTable(headers: string[], rows: string[][]): Table {
    const borderDef = { style: BorderStyle.SINGLE, size: 1, color: 'E5E7EB' }
    const borders   = { top: borderDef, bottom: borderDef, left: borderDef, right: borderDef, insideHorizontal: borderDef, insideVertical: borderDef }

    const headerRow = new TableRow({
      children: headers.map((h) =>
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, color: 'FFFFFF' })] })],
          shading: { fill: '1E40AF' },
          borders,
        }),
      ),
    })

    const dataRows = rows.map((row, ri) =>
      new TableRow({
        children: row.map((cell) =>
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: cell })] })],
            shading: ri % 2 === 0 ? { fill: 'F3F4F6' } : { fill: 'FFFFFF' },
            borders,
          }),
        ),
      }),
    )

    return new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [headerRow, ...dataRows],
    })
  }
}
